apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-otel.fullname" . }}-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-otel.labels" . | nindent 4 }}
data:
  config.yaml: |   {{ .Values.otelconfig | nindent 4  }}