apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-otel.fullname" . }}-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-otel.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]