apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-otel.fullname" . }}
  labels:
    {{- include "demo-otel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo-otel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-otel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-otel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.otel.repository }}:{{ .Values.image.otel.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.otel.pullPolicy }}
          args:
            - --config=/conf/config.yaml
          volumeMounts:
            - mountPath: /conf
              name: fso-agent-management-client-data
        - name: fso-agent-management-client
          image: {{ .Values.image.fso.repository }}:{{ .Values.image.fso.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: INSTANCE_UID
              value: INSTANCE_UID_VALUE
            - name: CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace # defaults to appdynamics
            - name: INSTALLED_TIME
              value: "INSTALLED_TIME_VALUE"
            - name: CLUSTER_ID
              value: "CLUSTER_ID_VALUE"
            - name: K8_OBJECT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          envFrom:
            - configMapRef:
                name: {{ include "demo-otel.fullname" . }}
            - secretRef:
                name: {{ include "demo-otel.fullname" . }}
          volumeMounts:
            - name: fso-agent-management-client-data
              mountPath: {{ .Values.config.file.path }}
      volumes:
        - name: fso-agent-management-client-data
          emptyDir: {}