apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-otel.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-otel.labels" . | nindent 4 }}
type: Opaque
data:
  OAUTH_SECRET: "OAUTH_SECRET_VALUE"